apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: model-serving
type: Opaque
stringData:
  MINIO_ACCESS_KEY: root
  MINIO_SECRET_KEY: password
  MINIO_ROOT_USER: root
  MINIO_ROOT_PASSWORD: password