# #remove this part if using GCP
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: gp2
# provisioner: ebs.csi.aws.com
# volumeBindingMode: WaitForFirstConsumer
# allowVolumeExpansion: true
# parameters:
#   type: gp2
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: model-serving
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2 #change to standard if using GKE
